import styled from "styled-components";
import Image from "next/image";
import { media } from "@/styles/theme";

export const Container = styled.div`max-width:1080px;margin:0 auto;padding:0 1rem;`;
export const SectionWhite = styled.section`background:#fff;`;
export const HeroSection = styled(SectionWhite)`min-height:480px;`;
export const HeroInner = styled(Container)`padding:4rem 1rem;display:flex;flex-direction:column;align-items:center;text-align:center;`;
export const HeroLogo = styled(Image)`object-fit:contain;margin-bottom:2rem;`;
export const HeroTitle = styled.h2`font-size:24px;font-weight:700;color:#333;margin-bottom:1rem;${media.lg}{font-size:32px;}`;
export const HeroDesc = styled.p`font-size:15px;color:#666;line-height:1.6;max-width:700px;margin-bottom:2rem;`;
export const DownloadRow = styled.div`display:flex;justify-content:center;align-items:center;gap:2.5rem;margin-bottom:1.5rem;`;
export const DownloadLink = styled.a`display:flex;flex-direction:column;align-items:center;gap:.5rem;transition:opacity .15s;&:hover{opacity:.7;}`;
export const DownloadIcon = styled(Image)`object-fit:contain;`;
export const DownloadLabel = styled.span`font-size:14px;color:#666;`;
export const SysReq = styled.p`font-size:13px;color:#999;`;
export const ScreenshotSection = styled(SectionWhite)`padding-bottom:4rem;`;
export const Screenshot = styled(Image)`width:100%;object-fit:contain;border-radius:.5rem;`;
export const CenterSection = styled(SectionWhite)`padding:4rem 0;`;
export const CenterTitle = styled.h2`font-size:28px;font-weight:700;color:#333;margin-bottom:1rem;text-align:center;${media.lg}{font-size:36px;}`;
export const CenterDesc = styled.p`font-size:15px;color:#666;line-height:1.6;max-width:700px;margin:0 auto .5rem;text-align:center;`;
export const CenterSub = styled.p`font-size:14px;color:#999;max-width:700px;margin:0 auto;text-align:center;`;
export const GraySection = styled.section`background:#f7f7f7;padding:4rem 0 5rem;`;
export const Split = styled.div`display:flex;flex-direction:column;align-items:center;gap:3rem;${media.lg}{flex-direction:row;}`;
export const Half = styled.div`width:100%;${media.lg}{width:50%;}`;
export const GifImage = styled.img`width:100%;object-fit:contain;border-radius:.5rem;`;
export const SplitTitle = styled.h2`font-size:22px;font-weight:700;color:#333;margin-bottom:.75rem;${media.lg}{font-size:28px;}`;
export const SplitSub = styled.p`font-size:18px;color:#555;margin-bottom:1.5rem;`;
export const DarkBtn = styled.a`display:inline-block;padding:.75rem 2rem;background:#2d2d2d;color:#fff;font-size:14px;font-weight:500;transition:background .15s;margin-bottom:1rem;&:hover{background:#444;}`;
export const Note = styled.p`font-size:12px;color:#999;font-style:italic;`;
export const CtaSection = styled.section`background:#f4f4f4;padding:5rem 0;`;
export const CtaSplit = styled.div`display:flex;flex-direction:column;align-items:center;gap:3rem;${media.lg}{flex-direction:row;}`;
export const CtaImageWrap = styled.div`width:100%;display:flex;justify-content:center;${media.lg}{width:50%;}`;
export const CtaImage = styled(Image)`object-fit:contain;`;
export const CtaText = styled.div`width:100%;text-align:center;${media.lg}{width:50%;text-align:left;}`;
export const CtaTitle = styled.h2`font-size:24px;font-weight:700;color:#333;margin-bottom:1rem;${media.lg}{font-size:30px;}`;
export const CtaDesc = styled.p`font-size:15px;color:#666;line-height:1.6;margin-bottom:2rem;`;
