import styled from "styled-components";
import Link from "next/link";
import { media } from "@/styles/theme";

export const HeroSection = styled.section`position:relative;display:flex;align-items:center;justify-content:center;overflow:hidden;min-height:680px;background:linear-gradient(135deg,#0f2235 0%,#1a3a5c 50%,#0d3347 100%);`;
export const HeroPattern = styled.div`position:absolute;inset:0;opacity:.1;background-image:radial-gradient(circle at 20% 50%,#4fa8d5 0%,transparent 50%),radial-gradient(circle at 80% 30%,#2a7ab5 0%,transparent 50%);`;
export const HeroInner = styled.div`position:relative;z-index:10;text-align:center;padding:0 1.5rem;max-width:800px;margin:0 auto;`;
export const Label = styled.p`font-size:13px;font-weight:600;color:#4fa8d5;text-transform:uppercase;letter-spacing:5px;margin-bottom:1.5rem;`;
export const HeroTitle = styled.h1`font-size:64px;font-weight:900;color:#fff;line-height:1;margin-bottom:1.5rem;letter-spacing:-.02em;${media.md}{font-size:80px;}`;
export const HeroAccent = styled.span`color:#4fa8d5;`;
export const HeroSubtitle = styled.p`font-size:20px;color:rgba(255,255,255,.8);line-height:1.6;margin-bottom:2.5rem;white-space:pre-line;${media.md}{font-size:24px;}`;
export const HeroBtnRow = styled.div`display:flex;flex-direction:column;gap:1rem;justify-content:center;${media.sm}{flex-direction:row;}`;
export const PrimaryLink = styled(Link)`display:inline-block;background:#4fa8d5;color:#fff;font-size:17px;padding:1rem 2.5rem;border-radius:9999px;font-weight:600;transition:background .15s;&:hover{background:#3a94c0;}`;
export const SectionWhite = styled.section`padding:6rem 0;background:#fff;`;
export const SectionBlue = styled.section`padding:6rem 0;background:#f4f8fb;`;
export const SectionDark = styled.section`padding:6rem 0;background:#0f2235;`;
export const Container = styled.div`max-width:1100px;margin:0 auto;padding:0 1.5rem;`;
export const IntroWrap = styled.div`display:flex;flex-direction:column;gap:4rem;align-items:center;${media.lg}{flex-direction:row;}`;
export const IntroImageWrap = styled.div`width:100%;${media.lg}{width:48%;}`;
export const IntroTextWrap = styled.div`width:100%;${media.lg}{width:52%;}`;
export const AboutLabel = styled(Label)`margin-bottom:.75rem;`;
export const Heading = styled.h2`font-size:36px;font-weight:700;color:#111827;margin-bottom:1.5rem;line-height:1.3;`;
export const Body = styled.p`font-size:17px;color:#6b7280;line-height:1.9;margin-bottom:1.5rem;`;
export const HighlightBox = styled.div`border-left:4px solid #4fa8d5;padding-left:1.25rem;padding-top:.25rem;padding-bottom:.25rem;`;
export const HighlightText = styled.p`font-size:17px;color:#374151;line-height:1.8;font-weight:500;`;
export const CenterHead = styled.div`text-align:center;margin-bottom:4rem;`;
export const Grid3 = styled.div`display:grid;gap:2rem;${media.md}{grid-template-columns:repeat(3,minmax(0,1fr));}`;
export const FeatureCard = styled.div`background:#fff;border-radius:1rem;padding:2rem;box-shadow:0 1px 2px rgba(0,0,0,.08);transition:box-shadow .15s;&:hover{box-shadow:0 4px 6px rgba(0,0,0,.12);}`;
export const NumBadge = styled.div`width:3rem;height:3rem;border-radius:.75rem;display:flex;align-items:center;justify-content:center;margin-bottom:1.5rem;color:#fff;font-weight:700;font-size:18px;background:linear-gradient(135deg,#1a3a5c,#4fa8d5);`;
export const CardTitle = styled.h3`font-size:19px;font-weight:700;color:#111827;margin-bottom:.75rem;line-height:1.4;`;
export const CardBody = styled.p`font-size:15px;color:#6b7280;line-height:1.8;`;
export const WorkFlowWrap = styled.div`position:relative;`;
export const WorkLine = styled.div`display:none;${media.md}{display:block;position:absolute;top:2.5rem;left:16.66%;right:16.66%;height:1px;background:rgba(79,168,213,.3);}`;
export const StepCard = styled.div`display:flex;flex-direction:column;align-items:center;text-align:center;`;
export const StepBubble = styled.div`width:5rem;height:5rem;border-radius:9999px;display:flex;align-items:center;justify-content:center;margin-bottom:1.5rem;color:#fff;font-weight:900;font-size:22px;position:relative;z-index:10;background:linear-gradient(135deg,#0f2235,#4fa8d5);`;
export const DarkHeading = styled(Heading)`color:#fff;text-align:center;`;
export const Split3 = styled.div`display:grid;gap:2.5rem;${media.md}{grid-template-columns:repeat(3,minmax(0,1fr));}`;
export const ChipWrap = styled.div`display:flex;flex-wrap:wrap;gap:.5rem;`;
export const Chip = styled.span`padding:.5rem 1rem;background:rgba(255,255,255,.1);color:#fff;font-size:14px;border-radius:9999px;border:1px solid rgba(255,255,255,.2);`;
export const ChipBlue = styled(Chip)`background:rgba(79,168,213,.2);color:#4fa8d5;border-color:rgba(79,168,213,.4);`;
export const EnvList = styled.ul`display:flex;flex-direction:column;gap:.5rem;`;
export const EnvItem = styled.li<{ $main?: boolean }>`display:flex;align-items:center;gap:.5rem;font-size:${({ $main }) => ($main ? "15px" : "13px")};color:${({ $main }) => ($main ? "rgba(255,255,255,.7)" : "rgba(255,255,255,.5)")};padding-left:${({ $main }) => ($main ? "0" : "1rem")};`;
export const Dot = styled.span<{ $main?: boolean }>`border-radius:9999px;flex-shrink:0;width:${({ $main }) => ($main ? "6px" : "4px")};height:${({ $main }) => ($main ? "6px" : "4px")};background:${({ $main }) => ($main ? "#4fa8d5" : "rgba(255,255,255,.3)")};`;
export const NoticeList = styled.div`margin-bottom:1rem;display:flex;flex-direction:column;gap:.25rem;font-size:14px;color:#4b5563;`;
export const TableWrap = styled.div`overflow-x:auto;border-radius:1rem;box-shadow:0 1px 2px rgba(0,0,0,.08);margin-bottom:2.5rem;`;
export const Table = styled.table`width:100%;font-size:14px;text-align:center;border-collapse:collapse;min-width:900px;`;
export const Th = styled.th`border:1px solid #e5e7eb;padding:.75rem 1rem;font-weight:600;color:#374151;background:#f3f4f6;`;
export const ThYellow = styled(Th)`background:#f8e581;color:#1f2937;`;
export const ThBlue = styled(Th)`background:#e8f4fd;color:#1a3a5c;`;
export const ThSubYellow = styled(Th)`background:#fdf4c0;`;
export const ThSubBlue = styled(Th)`background:#d6edf9;`;
export const Td = styled.td`border:1px solid #e5e7eb;padding:.75rem 1rem;color:#4b5563;`;
export const TdStrong = styled(Td)`font-weight:700;color:#111827;`;
export const TdBlue = styled(Td)`font-weight:600;color:#1a3a5c;`;
export const Grid2 = styled.div`display:grid;gap:2rem;${media.md}{grid-template-columns:repeat(2,minmax(0,1fr));}`;
export const SubHeading = styled.h3`font-size:16px;font-weight:700;color:#1f2937;margin-bottom:1rem;`;
export const SmallBody = styled.p`font-size:13px;color:#6b7280;margin-bottom:.75rem;`;
export const MiniTableWrap = styled.div`overflow:hidden;border-radius:.75rem;border:1px solid #e5e7eb;`;
export const MiniTable = styled.table`width:100%;font-size:14px;text-align:center;border-collapse:collapse;`;
export const MiniTh = styled.th`padding:.5rem 1rem;font-weight:600;color:#1f2937;background:#f8e581;border-right:1px solid #e5e7eb;`;
export const MiniTd = styled.td`padding:.625rem 1rem;color:#4b5563;border-top:1px solid #f3f4f6;`;
export const DarkCtaSection = styled.section`padding:6rem 0;background:linear-gradient(135deg,#0f2235 0%,#1a3a5c 100%);`;
export const CtaBox = styled.div`max-width:700px;margin:0 auto;padding:0 1.5rem;text-align:center;`;
export const CtaHeading = styled.h2`font-size:40px;font-weight:700;color:#fff;margin-bottom:1rem;`;
export const CtaDesc = styled.p`font-size:17px;color:rgba(255,255,255,.6);margin-bottom:2.5rem;`;
export const ContactRow = styled.div`display:flex;flex-direction:column;gap:1.5rem;justify-content:center;color:rgba(255,255,255,.5);font-size:15px;${media.sm}{flex-direction:row;}`;
export const ContactLink = styled.a`transition:color .15s;&:hover{color:rgba(255,255,255,.8);}`;
