import styled from "styled-components";
import Image from "next/image";
import { media } from "@/styles/theme";

export const Container = styled.div`max-width:1080px;margin:0 auto;padding:0 1rem;`;
export const HeroSection = styled.section`background:#1a1a2e;color:#fff;min-height:400px;`;
export const HeroInner = styled(Container)`padding:5rem 1rem;display:flex;flex-direction:column;align-items:center;text-align:center;`;
export const HeroTitle = styled.h1`font-size:36px;font-weight:700;margin-bottom:1rem;${media.lg}{font-size:48px;}`;
export const HeroSubtitle = styled.p`font-size:16px;color:#d1d5db;line-height:1.6;max-width:600px;`;
export const SectionWhite = styled.section`background:#fff;`;
export const SectionGray = styled.section`background:#f5f5f5;`;
export const SectionPad = styled(Container)`padding:5rem 1rem;`;
export const FeatureGrid = styled.div`display:grid;grid-template-columns:1fr;gap:2.5rem;${media.md}{grid-template-columns:repeat(3,minmax(0,1fr));}`;
export const FeatureCard = styled.div`text-align:center;`;
export const FeatureIcon = styled(Image)`margin:0 auto 1.5rem;object-fit:contain;`;
export const FeatureTitle = styled.h3`font-size:18px;font-weight:700;color:#333;margin-bottom:.75rem;${media.lg}{font-size:20px;}`;
export const FeatureDesc = styled.p`font-size:14px;color:#666;line-height:1.6;`;
export const SectionHeading = styled.h2`font-size:28px;font-weight:700;color:#333;margin-bottom:3rem;text-align:center;${media.lg}{font-size:34px;}`;
export const DownloadGrid5 = styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.5rem;margin-bottom:3rem;${media.sm}{grid-template-columns:repeat(3,minmax(0,1fr));}${media.md}{grid-template-columns:repeat(5,minmax(0,1fr));}`;
export const DownloadGrid4 = styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.5rem;margin-bottom:3rem;${media.sm}{grid-template-columns:repeat(3,minmax(0,1fr));}${media.md}{grid-template-columns:repeat(4,minmax(0,1fr));}`;
export const DownloadGrid2 = styled.div`display:grid;grid-template-columns:1fr;gap:1.5rem;${media.sm}{grid-template-columns:repeat(2,minmax(0,1fr));}`;
export const DownloadCard = styled.div`background:#fff;border-radius:.5rem;padding:1rem;box-shadow:0 1px 2px rgba(0,0,0,.08);text-align:center;`;
export const DownloadImage = styled(Image)`width:100%;object-fit:contain;margin-bottom:1rem;`;
export const DownloadBtn = styled.a`display:inline-block;padding:.5rem 1.25rem;background:#333;color:#fff;font-size:13px;font-weight:500;border-radius:.25rem;transition:background .15s;&:hover{background:#555;}`;
export const NoteBox = styled.div`background:#f9f9f9;border-radius:.5rem;padding:2rem;margin-bottom:3rem;`;
export const NoteLabel = styled.p`font-size:13px;color:#888;margin-bottom:.5rem;`;
export const NoteLabelStrong = styled.span`font-weight:600;color:#666;`;
export const NoteList = styled.ol`font-size:13px;color:#888;line-height:1.6;display:flex;flex-direction:column;gap:.25rem;list-style:decimal inside;`;
export const InfoSplit = styled.div`display:flex;flex-direction:column;align-items:center;gap:2.5rem;margin-bottom:4rem;${media.lg}{flex-direction:row;}`;
export const InfoSplitReverse = styled(InfoSplit)`${media.lg}{flex-direction:row-reverse;}`;
export const InfoHalf = styled.div`width:100%;${media.lg}{width:50%;}`;
export const InfoTitle = styled.h3`font-size:22px;font-weight:700;color:#333;margin-bottom:.5rem;${media.lg}{font-size:26px;}`;
export const InfoSub = styled.h4`font-size:18px;font-weight:600;color:#555;margin-bottom:1rem;`;
export const InfoDesc = styled.p`font-size:14px;color:#666;line-height:1.6;`;
export const InfoImageWrap = styled.div`width:100%;display:flex;justify-content:center;${media.lg}{width:50%;}`;
export const InfoImage = styled(Image)`object-fit:contain;width:100%;max-width:400px;`;
export const InfoImageRounded = styled(InfoImage)`border-radius:.5rem;`;
