import styled from "styled-components";
import Image from "next/image";
import Link from "next/link";
import { media } from "@/styles/theme";

export const HeroSection = styled.section`position:relative;padding:5rem 0;background:url('/images/partnership/shakeHands.jpg') center/cover no-repeat;`;
export const HeroOverlay = styled.div`position:absolute;inset:0;background:rgba(0,0,0,.5);`;
export const Container = styled.div`max-width:1080px;margin:0 auto;padding:0 1rem;`;
export const HeroInner = styled(Container)`position:relative;z-index:10;display:flex;flex-direction:column;gap:3rem;align-items:center;${media.lg}{flex-direction:row;}`;
export const HeroText = styled.div`color:#fff;width:100%;${media.lg}{width:50%;}`;
export const HeroLabel = styled.p`color:#ff6720;text-transform:uppercase;letter-spacing:.2em;font-size:14px;margin-bottom:1rem;`;
export const HeroTitle = styled.h1`font-size:32px;font-weight:900;margin-bottom:1.5rem;line-height:1.2;${media.lg}{font-size:40px;}`;
export const HeroDesc = styled.p`color:#e5e7eb;font-size:14px;line-height:2;`;
export const HeroImageWrap = styled.div`width:100%;display:flex;justify-content:center;${media.lg}{width:50%;}`;
export const HeroImage = styled(Image)`border-radius:.5rem;`;
export const SectionWhite = styled.section`padding:54px 0;background:#fff;`;
export const SectionGray = styled.section`padding:54px 0;background:#f1f1f1;`;
export const CenterTitle = styled.h2`font-size:30px;font-weight:500;color:#000;margin-bottom:1rem;text-align:center;`;
export const CenterDesc = styled.p`color:#666;font-size:14px;text-align:center;`;
export const PrimaryBtnLink = styled(Link)`display:inline-block;background:#ff6720;color:#fff;padding:.75rem 2rem;border-radius:.25rem;font-weight:600;transition:background .15s;text-transform:uppercase;letter-spacing:.08em;font-size:14px;&:hover{background:#e55e1d;}`;
export const CenterWrap = styled.div`text-align:center;`;
export const ExhibGrid = styled.div`display:grid;gap:2rem;${media.md}{grid-template-columns:repeat(3,minmax(0,1fr));}`;
export const EventCard = styled.div`border-radius:.5rem;overflow:hidden;box-shadow:0 10px 15px rgba(0,0,0,.12);`;
export const EventImageWrap = styled.div`position:relative;height:12rem;`;
export const EventBody = styled.div`padding:1.5rem;`;
export const EventTitle = styled.h3`font-weight:700;color:#000;margin-bottom:.5rem;`;
export const EventDesc = styled.p`color:#666;font-size:14px;`;
export const MailLink = styled.a`color:#ff6720;&:hover{text-decoration:underline;}`;
export const DarkSection = styled.section`padding:4rem 0;background:#1a1a2e;color:#fff;text-align:center;`;
export const DarkDesc = styled.p`color:#d1d5db;font-size:14px;margin-bottom:2rem;`;
export const TealBtn = styled(Link)`display:inline-block;background:#14b8a6;color:#fff;padding:.75rem 2rem;text-transform:uppercase;letter-spacing:.08em;font-size:14px;font-weight:600;transition:opacity .15s;&:hover{opacity:.9;}`;
