import styled from "styled-components";
import Image from "next/image";
import { media } from "@/styles/theme";

export const Container = styled.div`max-width:1080px;margin:0 auto;padding:0 1rem;`;
export const HeroSection = styled.section`background:#1a1a2e;color:#fff;min-height:480px;`;
export const HeroInner = styled(Container)`padding:5rem 1rem;display:flex;flex-direction:column;align-items:center;text-align:center;`;
export const HeroTitle = styled.h1`font-size:36px;font-weight:700;margin-bottom:1rem;${media.lg}{font-size:48px;}`;
export const HeroSub = styled.p`font-size:14px;color:#9ca3af;margin-bottom:2.5rem;`;
export const HeroImg = styled(Image)`object-fit:contain;width:100%;max-width:700px;`;
export const SectionWhite = styled.section`background:#fff;`;
export const SectionGray = styled.section`background:#f5f5f5;`;
export const SectionPad = styled(Container)`padding:5rem 1rem;`;
export const H2 = styled.h2`font-size:24px;font-weight:700;color:#333;text-align:center;margin-bottom:1rem;${media.lg}{font-size:30px;}`;
export const BodyCenter = styled.p`font-size:15px;color:#666;line-height:1.6;max-width:700px;margin:0 auto 3rem;text-align:center;`;
export const CompareGrid = styled.div`display:grid;grid-template-columns:1fr;gap:2rem;margin-bottom:4rem;${media.md}{grid-template-columns:repeat(2,minmax(0,1fr));}`;
export const CompareCol = styled.div`text-align:center;`;
export const CompareTitle = styled.h3`font-size:18px;font-weight:600;color:#333;margin-bottom:1rem;`;
export const CompareBox = styled.div`background:#f5f5f5;border-radius:.5rem;padding:2rem;display:flex;align-items:center;justify-content:center;min-height:300px;`;
export const CompareImg = styled(Image)`object-fit:contain;width:100%;max-width:300px;`;
export const FeatureGrid = styled.div`display:grid;grid-template-columns:1fr;gap:2.5rem;${media.md}{grid-template-columns:repeat(3,minmax(0,1fr));}`;
export const FeatureItem = styled.div`text-align:center;padding:0 1rem;`;
export const FeatureThumb = styled.div`margin-bottom:1.5rem;border-radius:.5rem;overflow:hidden;`;
export const FeatureImg = styled(Image)`width:100%;object-fit:cover;border-radius:.5rem;`;
export const FeatureTitle = styled.h3`font-size:20px;font-weight:700;color:#333;margin-bottom:1rem;${media.lg}{font-size:22px;}`;
export const FeatureDesc = styled.p`font-size:14px;color:#666;line-height:1.6;`;
export const CertImg = styled(Image)`margin:0 auto 2rem;`;
export const GalleryGrid = styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;${media.sm}{grid-template-columns:repeat(3,minmax(0,1fr));}${media.md}{grid-template-columns:repeat(5,minmax(0,1fr));}`;
export const GalleryImg = styled(Image)`width:100%;object-fit:cover;border-radius:.5rem;box-shadow:0 1px 2px rgba(0,0,0,.08);`;
export const LineupWrap = styled.div`display:flex;flex-direction:column;gap:2.5rem;`;
export const LineupCard = styled.div<{ $reverse:boolean }>`display:flex;flex-direction:column;align-items:center;gap:2rem;background:#fff;border-radius:.5rem;padding:1.5rem;box-shadow:0 1px 2px rgba(0,0,0,.08);${media.lg}{flex-direction:${({$reverse})=>$reverse?'row-reverse':'row'};}`;
export const LineupImgCol = styled.div`width:100%;display:flex;justify-content:center;${media.lg}{width:40%;}`;
export const LineupImg = styled(Image)`object-fit:contain;border-radius:.5rem;max-height:300px;`;
export const LineupTextCol = styled.div`width:100%;${media.lg}{width:60%;}`;
export const LineupName = styled.h3`font-size:20px;font-weight:700;color:#333;margin-bottom:.75rem;${media.lg}{font-size:22px;}`;
export const LineupDesc = styled.p`font-size:14px;color:#666;line-height:1.6;margin-bottom:1rem;`;
export const ProductInfoLabel = styled.p`font-size:12px;color:#999;font-weight:500;text-transform:uppercase;letter-spacing:.08em;margin-bottom:.25rem;`;
export const ProductInfoText = styled.p`font-size:13px;color:#888;`;
