import styled from "styled-components";
import Image from "next/image";
import Link from "next/link";
import { media } from "@/styles/theme";

export const Container = styled.div`max-width:1080px;margin:0 auto;padding:0 1rem;`;
export const SectionWhite = styled.section`background:#fff;`;
export const SectionGray = styled.section`background:#f5f5f5;`;
export const HeroSection = styled.section`background:#1a1a2e;color:#fff;overflow:hidden;min-height:560px;`;
export const HeroInner = styled(Container)`padding:4rem 1rem;display:flex;flex-direction:column;align-items:center;gap:2rem;min-height:560px;${media.lg}{flex-direction:row;}`;
export const HeroHalf = styled.div`width:100%;z-index:10;text-align:center;${media.lg}{width:50%;text-align:left;}`;
export const HeroTitle = styled.h1`font-size:36px;font-weight:700;line-height:1.2;margin-bottom:1.5rem;${media.lg}{font-size:46px;}`;
export const HeroSub = styled.span`font-size:18px;font-weight:400;color:#9ca3af;${media.lg}{font-size:20px;}`;
export const HeroDesc = styled.p`font-size:15px;color:#d1d5db;line-height:1.6;margin-bottom:2rem;max-width:480px;margin-left:auto;margin-right:auto;${media.lg}{margin-left:0;margin-right:0;}`;
export const TealBtn = styled.a`display:inline-block;padding:.75rem 2rem;background:#39d2cc;color:#fff;font-size:14px;font-weight:500;border-radius:.25rem;transition:background .15s;&:hover{background:#2db8b3;}`;
export const HeroImageWrap = styled(HeroHalf)`display:flex;justify-content:center;`;
export const HeroImage = styled(Image)`object-fit:contain;max-height:400px;`;
export const CenterSection = styled(SectionWhite)`padding:5rem 0;text-align:center;`;
export const CenterTitle = styled.h2`font-size:26px;font-weight:700;color:#333;margin-bottom:1.5rem;${media.lg}{font-size:32px;}`;
export const CenterDesc = styled.p`font-size:15px;color:#666;line-height:1.8;max-width:700px;margin:0 auto;`;
export const FeatureSection = styled(SectionGray)`padding:5rem 0;`;
export const Split = styled.div`display:flex;flex-direction:column;align-items:center;gap:3rem;${media.lg}{flex-direction:row;}`;
export const SplitReverse = styled(Split)`${media.lg}{flex-direction:row-reverse;}`;
export const Half = styled.div`width:100%;${media.lg}{width:50%;}`;
export const HalfImageWrap = styled(Half)`display:flex;justify-content:center;`;
export const HalfImage = styled(Image)`width:100%;max-width:480px;object-fit:contain;`;
export const HalfImageRound = styled(HalfImage)`border-radius:.5rem;`;
export const Tag = styled.h5`font-size:14px;color:#39d2cc;font-weight:600;margin-bottom:.5rem;`;
export const MidTitle = styled.h4`font-size:22px;font-weight:700;color:#333;margin-bottom:1rem;${media.lg}{font-size:26px;}`;
export const MidDesc = styled.p`font-size:15px;color:#666;line-height:1.6;`;
export const PurchaseSection = styled(SectionWhite)`padding:4rem 0;text-align:center;`;
export const PurchaseDesc = styled.p`font-size:15px;color:#666;line-height:1.6;margin:0 auto 1.5rem;max-width:600px;`;
export const DarkBtn = styled.a`display:inline-block;padding:.75rem 2rem;background:#333;color:#fff;font-size:14px;font-weight:500;border-radius:.25rem;transition:background .15s;&:hover{background:#555;}`;
export const OutlineBtn = styled.a`display:inline-block;padding:.625rem 1.5rem;border:1px solid #333;color:#333;font-size:14px;font-weight:500;border-radius:.25rem;transition:all .15s;&:hover{background:#333;color:#fff;}`;
export const StepsGrid = styled.div`display:grid;grid-template-columns:1fr;gap:2rem;${media.md}{grid-template-columns:repeat(3,minmax(0,1fr));}`;
export const StepCard = styled.div`text-align:center;background:#f9f9f9;border-radius:.5rem;padding:1.5rem;`;
export const StepTitle = styled.h5`font-size:16px;font-weight:700;color:#39d2cc;margin-bottom:.75rem;`;
export const StepDesc = styled.p`font-size:14px;color:#666;line-height:1.6;`;
export const RouteBtn = styled(Link)`display:inline-block;padding:.625rem 1.5rem;border:1px solid #333;color:#333;font-size:14px;font-weight:500;border-radius:.25rem;transition:all .15s;&:hover{background:#333;color:#fff;}`;
