import styled from "styled-components";
import Link from "next/link";
import { media } from "@/styles/theme";

export const Main = styled.main`font-family:Montserrat,sans-serif;`;
export const HeroSection = styled.section`position:relative;display:flex;align-items:center;justify-content:center;overflow:hidden;background-color:#f8e581;background-image:url('/images/pokoro/main_bg.png');background-size:cover;background-position:70% 50%;background-repeat:no-repeat;min-height:900px;`;
export const HeroInner = styled.div`position:relative;z-index:10;text-align:center;padding:0 1rem;`;
export const HeroTitle = styled.h1`font-size:52px;font-weight:700;color:#000;line-height:1.2;margin-bottom:1rem;`;
export const Sup = styled.sup`font-size:16px;vertical-align:super;`;
export const HeroSub1 = styled.p`font-size:22px;font-weight:600;color:#000;margin-bottom:.25rem;`;
export const HeroSub2 = styled.p`font-size:30px;font-weight:600;color:#000;margin-bottom:3rem;`;
export const BuyBtn = styled(Link)`display:inline-block;background:#000;color:#fff;font-size:20px;padding:1.25rem 2.5rem;border-radius:9999px;font-weight:600;transition:background .15s;&:hover{background:rgba(0,0,0,.75);}`;
export const SectionWhite = styled.section`padding:6rem 0;background:#fff;`;
export const SectionGray = styled.section`padding:6rem 0;background:#f5f5f5;`;
export const SectionYellow = styled.section`padding:6rem 0;background:#f8e581;`;
export const Container = styled.div`max-width:1200px;margin:0 auto;padding:0 1.5rem;`;
export const Center = styled.div`text-align:center;`;
export const Label = styled.p`font-size:15px;font-weight:600;color:rgba(0,0,0,.4);text-transform:uppercase;letter-spacing:4px;margin-bottom:.75rem;`;
export const Heading = styled.h2`font-size:42px;font-weight:700;color:#000;`;
export const DeviceImage = styled.img`width:320px;height:auto;${media.md}{width:420px;}`;
export const FeaturesList = styled.ul`display:flex;flex-wrap:wrap;justify-content:center;gap:2rem;`;
export const FeatureItem = styled.li`display:flex;flex-direction:column;align-items:center;gap:.5rem;width:100px;`;
export const FeatureIcon = styled.img`width:100px;height:100px;border-radius:1rem;`;
export const FeatureLabel = styled.span`font-size:13px;font-weight:700;color:#000;text-align:center;line-height:1.2;`;
export const Split = styled.div`display:flex;flex-direction:column;gap:3rem;align-items:center;${media.lg}{flex-direction:row;}`;
export const SplitReverse = styled(Split)`${media.lg}{flex-direction:row-reverse;}`;
export const Half = styled.div`width:100%;${media.lg}{width:50%;}`;
export const RoundedImg = styled.img`width:100%;height:auto;border-radius:1rem;`;
export const BodyLg = styled.p`font-size:22px;color:#000;line-height:1.6;margin-bottom:1rem;`;
export const BodyMd = styled.p`font-size:18px;color:rgba(0,0,0,.55);line-height:1.7;`;
export const AnswerBox = styled.div`text-align:center;background:#fff;border-radius:1.5rem;padding:4rem 2rem;box-shadow:0 1px 2px rgba(0,0,0,.08);`;
export const AnswerHeading = styled.h2`font-size:32px;font-weight:700;color:#000;line-height:1.4;margin-bottom:1.5rem;${media.md}{font-size:40px;}`;
export const Highlight = styled.span`background:linear-gradient(transparent 50%,#f8e581 50%);`;
export const CardGrid3 = styled.div`display:grid;gap:2rem;${media.md}{grid-template-columns:repeat(3,minmax(0,1fr));}`;
export const Card = styled.div`background:#fff;border-radius:1.5rem;padding:2rem;display:flex;flex-direction:column;gap:1rem;`;
export const Num = styled.div`width:3rem;height:3rem;background:#000;border-radius:9999px;display:flex;align-items:center;justify-content:center;`;
export const NumText = styled.span`color:#fff;font-size:20px;font-weight:700;`;
export const CardTitle = styled.h3`font-size:22px;font-weight:700;color:#000;`;
export const CardDesc = styled.p`font-size:16px;color:rgba(0,0,0,.6);line-height:1.7;`;
export const TapGrid = styled.div`display:grid;gap:1.5rem;margin-top:4rem;${media.md}{grid-template-columns:repeat(3,minmax(0,1fr));}`;
export const TapLabel = styled.h3`font-size:28px;font-weight:700;color:#000;margin-top:1rem;`;
export const DesktopOnly = styled.img`display:none;width:100%;height:auto;border-radius:1rem;${media.md}{display:block;}`;
export const MobileOnly = styled.img`width:100%;max-width:28rem;margin:0 auto;height:auto;border-radius:1rem;${media.md}{display:none;}`;
export const SectionStack = styled.div`display:flex;flex-direction:column;gap:6rem;`;
export const PairImages = styled.div`display:flex;flex-direction:column;gap:1rem;justify-content:center;${media.sm}{flex-direction:row;}`;
export const PairImage = styled.img`width:100%;height:auto;${media.sm}{width:48%;}`;
export const CtaSection = styled.section`background:#f8e581;padding:6rem 0;`;
export const CtaBox = styled.div`max-width:800px;margin:0 auto;padding:0 1.5rem;text-align:center;`;
