import styled from "styled-components";
import { media } from "@/styles/theme";

export const Page = styled.div`background:#fff;min-height:100vh;font-family:Arial,sans-serif;`;
export const HeroSection = styled.section`position:relative;width:100%;background:#f8f9fa;padding-top:100px;overflow:hidden;border-bottom:1px solid #e5e7eb;`;
export const HeroBg = styled.div`position:absolute;inset:0;z-index:0;`;
export const HeroBlurTop = styled.div`position:absolute;top:0;left:0;width:400px;height:400px;background:linear-gradient(to bottom right,#ffcccb,#e2d5f8,transparent);opacity:.6;filter:blur(64px);`;
export const HeroBlurBottom = styled.div`position:absolute;bottom:0;right:0;width:500px;height:300px;background:linear-gradient(to top,#f0f4f8,transparent);opacity:.8;filter:blur(40px);`;
export const Container = styled.div`max-width:1080px;margin:0 auto;padding:0 1rem;`;
export const HeroInner = styled(Container)`position:relative;z-index:10;padding:4rem 1rem 6rem;`;
export const HeroTitle = styled.h1`font-size:80px;font-weight:800;color:#000;line-height:1.1;letter-spacing:-.02em;${media.md}{font-size:56px;}`;
export const WaveWrap = styled.div`position:absolute;bottom:-2px;left:0;width:100%;overflow:hidden;line-height:0;z-index:20;`;
export const WaveSvg = styled.svg`display:block;width:calc(110% + 1.3px);height:100px;`;
export const CiSection = styled.section`max-width:1080px;margin:0 auto;padding:6rem 1rem;border-bottom:1px solid #d1d5db;`;
export const BiSection = styled.section`max-width:1080px;margin:0 auto;padding:6rem 1rem 8rem;`;
export const SectionTitle = styled.h2`font-size:40px;font-weight:700;color:#333;margin-bottom:3rem;`;
export const SubTitle = styled.h3`font-size:24px;font-weight:500;color:#444;margin-bottom:2rem;`;
export const ColorRow = styled.div`display:flex;gap:2rem;flex-wrap:wrap;`;
export const ColorCard = styled.div<{ $bg: string; $shadow: string }>`width:300px;height:160px;background:${({ $bg }) => $bg};border-radius:30px;box-shadow:${({ $shadow }) => $shadow};display:flex;align-items:center;padding:2rem;transition:transform .15s;&:hover{transform:translateY(-4px);}`;
export const ColorText = styled.p`color:#fff;font-size:24px;font-weight:500;line-height:1.5;`;
export const ColorTextDark = styled(ColorText)`color:#666;`;
export const LogoGrid4 = styled.div`display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;align-items:stretch;border:1px solid #f3f4f6;${media.md}{grid-template-columns:repeat(2,minmax(0,1fr));}`;
export const LogoCell = styled.div<{ $bg?: string }>`padding:2rem;display:flex;justify-content:center;align-items:center;background:${({ $bg }) => $bg ?? "#fff"};`;
export const LogoImg = styled.img`max-height:60px;width:auto;`;
export const StoryWrap = styled.div`display:flex;justify-content:center;padding:2rem 0;`;
export const StoryImg = styled.img`max-width:100%;width:auto;`;
export const Palette = styled.div`display:flex;border-radius:16px;overflow:hidden;box-shadow:0 10px 30px rgba(0,0,0,.1);${media.md}{flex-direction:column;}`;
export const PaletteItem = styled.div<{ $bg: string }>`flex:1;height:220px;background:${({ $bg }) => $bg};display:flex;flex-direction:column;justify-content:center;padding:2rem;align-items:center;text-align:center;`;
export const PaletteText = styled.p<{ $dark?: boolean }>`color:${({ $dark }) => ($dark ? "#666" : "#fff")};font-size:24px;font-weight:500;line-height:1.6;`;
export const LogoStack = styled.div`display:flex;flex-direction:column;gap:1.5rem;`;
export const LogoStrip = styled.div<{ $bg?: string }>`display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;padding:2rem;align-items:center;background:${({ $bg }) => $bg ?? "#fff"};border:${({ $bg }) => ($bg ? "none" : "1px solid #f3f4f6")};${media.md}{grid-template-columns:repeat(2,minmax(0,1fr));}`;
export const SymbolBar = styled.div<{ $bg?: string }>`display:flex;justify-content:space-between;padding:2rem;align-items:center;background:${({ $bg }) => $bg ?? "#fff"};border:${({ $bg }) => ($bg ? "none" : "1px solid #f3f4f6")};${media.md}{flex-direction:column;gap:1rem;}`;
export const SymbolLabel = styled.div<{ $dark?: boolean }>`font-size:24px;font-weight:500;color:${({ $dark }) => ($dark ? "#fff" : "#444")};`;
export const SymbolImages = styled.div`display:flex;gap:4rem;padding-right:4rem;${media.md}{padding-right:0;}`;
