import styled from "styled-components";
import Image from "next/image";
import Link from "next/link";
import { media } from "@/styles/theme";

export const HeroSection = styled.section`position:relative;padding:5rem 0;background:url('/images/soundpen/Neo-04_01-1024x684-1.jpg') center/cover no-repeat;`;
export const HeroOverlay = styled.div`position:absolute;inset:0;background:rgba(0,0,0,.5);`;
export const Container = styled.div`max-width:1080px;margin:0 auto;padding:0 1rem;`;
export const HeroInner = styled(Container)`position:relative;z-index:10;display:flex;flex-direction:column;gap:3rem;align-items:center;${media.lg}{flex-direction:row;}`;
export const HeroText = styled.div`color:#fff;width:100%;${media.lg}{width:50%;}`;
export const HeroLabel = styled.p`color:#ff6720;text-transform:uppercase;letter-spacing:.2em;font-size:14px;margin-bottom:1rem;`;
export const HeroTitle = styled.h1`font-size:32px;font-weight:900;margin-bottom:1.5rem;line-height:1.2;${media.lg}{font-size:40px;}`;
export const HeroDesc = styled.p`color:#e5e7eb;font-size:14px;line-height:2;margin-bottom:2rem;`;
export const HeroBtnRow = styled.div`display:flex;gap:1rem;flex-wrap:wrap;`;
export const OutlineBtn = styled(Link)`display:inline-block;background:#fff;color:#ff6720;border:1px solid #ff6720;padding:.75rem 2rem;border-radius:.25rem;font-weight:600;transition:background .15s;text-transform:uppercase;letter-spacing:.08em;font-size:14px;&:hover{background:#f9fafb;}`;
export const GreenBtn = styled(Link)`display:inline-block;background:#03c75a;color:#fff;padding:.75rem 2rem;border-radius:.25rem;font-weight:600;transition:opacity .15s;text-transform:uppercase;letter-spacing:.08em;font-size:14px;&:hover{opacity:.9;}`;
export const HeroImageWrap = styled.div`width:100%;display:flex;justify-content:center;${media.lg}{width:50%;}`;
export const HeroImage = styled(Image)`filter:drop-shadow(0 20px 25px rgba(0,0,0,.4));`;
export const SectionWhite = styled.section`padding:54px 0;background:#fff;`;
export const SectionGray = styled.section`padding:54px 0;background:#f1f1f1;`;
export const CenterTitle = styled.h2`font-size:30px;font-weight:500;color:#000;margin-bottom:1.5rem;text-align:center;`;
export const CenterBody = styled.p`color:#666;font-size:14px;line-height:2;text-align:center;`;
export const ProductGrid = styled.div`display:grid;grid-template-columns:1fr;gap:2rem;${media.md}{grid-template-columns:repeat(2,minmax(0,1fr));}${media.lg}{grid-template-columns:repeat(4,minmax(0,1fr));}`;
export const ProductCard = styled.div`background:#fff;border-radius:.75rem;padding:2rem;text-align:center;box-shadow:0 1px 2px rgba(0,0,0,.08);`;
export const ProductImageWrap = styled.div`margin-bottom:1.5rem;display:flex;justify-content:center;`;
export const ProductImage = styled(Image)`height:12rem;width:auto;object-fit:contain;`;
export const ProductName = styled.h3`font-size:20px;font-weight:700;color:#000;`;
export const Split = styled.div`display:flex;flex-direction:column;gap:3rem;align-items:center;${media.lg}{flex-direction:row;}`;
export const SplitLeft45 = styled.div`width:100%;${media.lg}{width:45%;}`;
export const SplitRight55 = styled.div`width:100%;${media.lg}{width:55%;}`;
export const FeatureImg = styled(Image)`width:100%;max-width:490px;height:auto;margin:0 auto;`;
export const FeatureStack = styled.div`display:flex;flex-direction:column;gap:2rem;`;
export const FeatureTitle = styled.h3`font-size:20px;font-weight:700;color:#000;margin-bottom:.75rem;`;
export const FeatureDesc = styled.p`color:#666;font-size:14px;line-height:2;`;
